import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

export async function POST(req: NextRequest) {
    try {
        if (!process.env.GEMINI_API_KEY) {
            return NextResponse.json(
                { error: "GEMINI_API_KEY environment variable is missing. Please add it to your .env file." },
                { status: 500 }
            );
        }

        const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

        const body = await req.json();
        const { messages, userProfile, skills } = body;

        if (!messages || !Array.isArray(messages)) {
            return NextResponse.json({ error: "Invalid messages format" }, { status: 400 });
        }

        // Build the system prompt using the user's data
        const systemInstruction = `
You are the AI Career Analyst & Coach in a gamified skill-tracking app called "Solo Leveler".
Your goal is to act as a mentor, analyzing the user's skillset and providing tailored career pathing, actionable practice tasks, and market trend insights.

--- USER PROFILE ---
Name: ${userProfile?.display_name || 'Anonymous User'}
Vocation: ${userProfile?.education_or_job || 'Not specified'}
Age: ${userProfile?.age || 'Not specified'}

--- CURRENT SKILLS ---
${skills && skills.length > 0
                ? skills.map((s: any) => `- ${s.name} (Lv.${s.level}, Mastery: ${s.mastery}%, Difficulty: ${s.difficulty}/10, Category: ${s.bucket})`).join('\n')
                : 'No skills added yet.'
            }

--- INSTRUCTIONS ---
1. You are having a direct, friendly conversation with the user.
2. If they ask what to learn next, recommend skills with high market ROI that complement their CURRENT SKILLS.
3. If they ask for a practice task, generate a specific, actionable micro-step or project related to one of their skills.
4. If they ask about your rating system (e.g. why their mastery is low/high), use their skill list and explain that ratings are determined by the complexity of the description they provided when adding the skill.
5. Keep your responses concise, engaging, and formatted using Markdown (bolding, lists). Don't output huge walls of text. Be conversational!
`;

        // Format history for the Gemini API
        // @google/genai uses 'user' and 'model' for roles. (Our frontend uses 'user' and 'coach')
        const contents = messages.map((msg: any) => ({
            role: msg.role === 'coach' ? 'model' : 'user',
            parts: [{ text: msg.content }],
        }));

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: contents,
            config: {
                systemInstruction: systemInstruction,
                temperature: 0.7,
            },
        });

        if (!response.text) {
            return NextResponse.json({ error: "No response generated by Gemini" }, { status: 500 });
        }

        return NextResponse.json({ reply: response.text });

    } catch (error: any) {
        console.error("Coach API Error:", error);
        return NextResponse.json(
            { error: "An error occurred while generating a response." },
            { status: 500 }
        );
    }
}
